FROM node:14.17.4-alpine3.14

ARG NODE_ENV=production
ENV NODE_ENV $NODE_ENV

# Default to port 8000 for node
ARG PORT=8000
ENV PORT $PORT
EXPOSE $PORT

RUN mkdir /opt/node_app && chown node:node /opt/node_app
WORKDIR /opt/node_app

USER node
COPY --chown=node:node server/package*.json ./
RUN npm i npm@7.21.0 -g 
RUN npm install --no-optional && npm cache clean --force
ENV PATH /opt/node_app/node_modules/.bin:$PATH

COPY --chown=node:node server/ ./

ENTRYPOINT ["node", "./src/app.js"]
