# React app
FROM node:14.17.4-alpine3.14 as build

WORKDIR /app

COPY web/package*.json ./
RUN npm ci
COPY web/ ./

RUN npm run build

# Nginx
FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
RUN rm /etc/nginx/conf.d/default.conf
COPY infra/nginx.conf /etc/nginx/conf.d/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
