export const PRIMARY = '#1563ff';
export const SECONDARY = '#d0e0ff';
export const BLACK = '#000000';
export const WHITE = '#ffffff';
export const IRREVERSIBLE_ACTION = '#f44336';
export const GRAY1 = '#333333'; // font
export const GRAY2 = '#7f7f86'; // modals, icons, inactive states
export const GRAY3 = '#e0e0e0'; // border
export const GRAY4 = '#f9f9f9'; // low contrast background: inner divs
export const MUI_INPUT_BORDER = '#bdbdbd';
