const POST_SCHEMA_CONFIGS = Object.freeze({
  MAX_LEN_TEXT: 3000,
  MIN_LEN_TEXT: 0,
  MAX_NUM_LIST: 5,
  MAX_LEN_EDITOR: 10000,
  MIN_LEN_EDITOR: 0,
  MAX_NUM_IMAGES: 2,
  MAX_NUM_TOPICS: 5,
  MIN_NUM_TOPICS: 1,
  MAX_LEN_TOPIC: 30,
});

module.exports = POST_SCHEMA_CONFIGS;
