export const FORM_SCHEMA_CONFIGS = Object.freeze({
  MAX_IMAGE_COMP: 1,
  MAX_NUM_CONTENT: 10,
  MIN_NUM_CONTENT: 1,
  MAX_LEN_TYPE: 100,
  MIN_LEN_TYPE: 1,
  MAX_LEN_KEY_OF_CONTENT: 100,
});

export const POST_SCHEMA_CONFIGS = Object.freeze({
  MAX_LEN_TEXT: 3000,
  MIN_LEN_TEXT: 1,
  MAX_NUM_LIST: 5,
  MAX_LEN_EDITOR: 10000,
  MIN_LEN_EDITOR: 1,
  MAX_NUM_IMAGES: 2,
  MAX_NUM_TOPICS: 5,
  MIN_NUM_TOPICS: 1,
  MAX_LEN_TOPIC: 30,
});
