const FORM_SCHEMA_CONFIGS = Object.freeze({
  MAX_IMAGE_COMP: 1,
  MAX_NUM_CONTENT: 10,
  MIN_NUM_CONTENT: 1,
  MAX_LEN_TYPE: 100,
  MIN_LEN_TYPE: 1,
  MAX_LEN_KEY_OF_CONTENT: 100,
});

export default FORM_SCHEMA_CONFIGS;
